name: RN Android No ProGuard Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        abi: [ x86, x86_64, arm64-v8a ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install JS Dependencies
        run: npm ci

      - name: Restore Gradle Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-${{ hashFiles('android/**/build.gradle','android/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Expo Prebuild (if needed)
        run: |
          if [ ! -d android ]; then
            echo "android 目录不存在，执行 expo prebuild"
            npx expo prebuild --platform android
          else
            echo "android 目录已存在，跳过 prebuild"
          fi

      - name: Copy network security config
        run: |
          mkdir -p android/app/src/main/res/xml/
          cp assets/network_security_config.xml android/app/src/main/res/xml/

      - name: Enable ABI splits in build.gradle
        run: |
          # 只插入一次 splits 配置，避免重复
          if ! grep -q "splits {" android/app/build.gradle; then
            perl -i -pe 's/(android\s*\{)/\1\n  splits {\n    abi {\n      enable true\n      reset()\n      include "${{ matrix.abi }}"\n      universalApk true\n    }\n  }/' android/app/build.gradle
          fi

      - name: Disable ProGuard completely
        run: |
          # 完全禁用ProGuard/R8来测试是否是混淆导致的闪退
          echo "完全禁用ProGuard/R8进行测试构建"
          
          # 确保release配置中禁用了所有优化
          if ! grep -q "minifyEnabled false" android/app/build.gradle; then
            perl -i -pe 's/(release\s*\{)/\1\n            minifyEnabled false\n            shrinkResources false/' android/app/build.gradle
          fi
          
          echo "ProGuard已被禁用"

      - name: Setup Android Keystore
        run: |
          mkdir -p android/app
          echo "${{ secrets.KEYSTORE_B64 }}" | base64 -d > android/app/keystore.jks

      - name: Set up signing config env
        run: |
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV

      - name: Assemble for ${{ matrix.abi }}
        run: |
          cd android
          ./gradlew assembleRelease \
            -PcdvAbi="${{ matrix.abi }}" \
            -Dorg.gradle.jvmargs="-Xmx4g -XX:MaxMetaspaceSize=512m" \
            --no-daemon \
            --stacktrace
        env:
          NODE_ENV: production

      - name: Collect APK
        run: mkdir -p output && cp android/app/build/outputs/apk/release/app-${{ matrix.abi }}-release.apk output/

      - name: Upload APK ${{ matrix.abi }}
        uses: actions/upload-artifact@v4
        with:
          name: apk-no-proguard-${{ matrix.abi }}
          path: output/app-${{ matrix.abi }}-release.apk

  universal:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install JS Dependencies
        run: npm ci

      - name: Restore Gradle Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-${{ hashFiles('android/**/build.gradle','android/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Expo Prebuild (if needed)
        run: |
          if [ ! -d android ]; then
            echo "android 目录不存在，执行 expo prebuild"
            npx expo prebuild --platform android
          else
            echo "android 目录已存在，跳过 prebuild"
          fi

      - name: Copy network security config
        run: |
          mkdir -p android/app/src/main/res/xml/
          cp assets/network_security_config.xml android/app/src/main/res/xml/

      - name: Disable ProGuard completely
        run: |
          # 完全禁用ProGuard/R8来测试是否是混淆导致的闪退
          echo "完全禁用ProGuard/R8进行测试构建"
          
          # 确保release配置中禁用了所有优化
          if ! grep -q "minifyEnabled false" android/app/build.gradle; then
            perl -i -pe 's/(release\s*\{)/\1\n            minifyEnabled false\n            shrinkResources false/' android/app/build.gradle
          fi
          
          echo "ProGuard已被禁用"

      - name: Setup Android Keystore
        run: |
          mkdir -p android/app
          echo "${{ secrets.KEYSTORE_B64 }}" | base64 -d > android/app/keystore.jks

      - name: Set up signing config env
        run: |
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV

      - name: Build Universal APK
        run: |
          cd android
          ./gradlew assembleRelease \
            -Dorg.gradle.jvmargs="-Xmx4g -XX:MaxMetaspaceSize=512m" \
            --no-daemon \
            --stacktrace
        env:
          NODE_ENV: production

      - name: Collect Universal APK
        run: mkdir -p output && cp android/app/build/outputs/apk/release/app-universal-release.apk output/

      - name: Upload Universal APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-no-proguard-universal
          path: output/app-universal-release.apk

  release:
    needs: [ build, universal ]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Get Version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }} (No ProGuard)
          files: |
            dist/**/*.apk

  push-to-release:
    needs: [ build, universal ]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: latest

      - name: Push to Latest Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest-no-proguard
          title: "Latest Build (No ProGuard Test)"
          files: |
            latest/**/*.apk 